FROM clojure:lein

RUN apt-get update
RUN apt-get install -y jq
RUN apt-get install -y zip
RUN apt-get install -y python
RUN apt-get install -y python-pip
RUN pip install --upgrade pip
RUN pip install awscli --upgrade
